// <auto-generated />
using System;
using DocumentsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentsAPI.Migrations
{
    [DbContext(typeof(DocumentsAPIContext))]
    partial class DocumentsAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentsAPI.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentText")
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.ToTable("Document");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 93, DateTimeKind.Local).AddTicks(2401),
                            DocumentTitle = "Lim Doc",
                            DocumentType = 0
                        },
                        new
                        {
                            DocumentId = 2,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(5621),
                            DocumentTitle = "Simple Doc",
                            DocumentType = 0
                        },
                        new
                        {
                            DocumentId = 3,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(5692),
                            DocumentTitle = "More Simple Doc",
                            DocumentType = 0
                        },
                        new
                        {
                            DocumentId = 4,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(5701),
                            DocumentImage = "https://images.unsplash.com/photo-1606694582797-0324662ab736?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=726&q=80",
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "Fake Doc",
                            DocumentType = 2
                        },
                        new
                        {
                            DocumentId = 5,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(7773),
                            DocumentImage = "https://images.unsplash.com/photo-1457694587812-e8bf29a43845?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=751&q=80",
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "Foko Doc",
                            DocumentType = 2
                        },
                        new
                        {
                            DocumentId = 6,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(7834),
                            DocumentImage = "https://images.unsplash.com/photo-1603796846097-bee99e4a601f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80",
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "Foka Doc",
                            DocumentType = 2
                        },
                        new
                        {
                            DocumentId = 7,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(7841),
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "New Custom Doc",
                            DocumentType = 1
                        },
                        new
                        {
                            DocumentId = 8,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(7846),
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "Better Custom Doc",
                            DocumentType = 1
                        },
                        new
                        {
                            DocumentId = 9,
                            CreationDate = new DateTime(2020, 12, 1, 15, 51, 56, 97, DateTimeKind.Local).AddTicks(7851),
                            DocumentText = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
                            DocumentTitle = "The best Custom Doc",
                            DocumentType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
